### ISSUE TITLE
Student email id issue

### ISSUE THREAD

**Issue by deepakkoirala** [education/guide#41] opened 2017-06-28 21:22 UTC
I have a student email id from my college that is **deepak@mycollege.edu.np.** So will this email be accepted for student pack ?  As I have heard only it has to be .edu email but my email is .edu.np.

So how does it work ? It would help a lot.

**Comment by tarebyte** [comment] 2017-06-28 22:52
@deepakkoirala this looks like a duplicate of https://github.com/education/classroom/issues/973.

You can contact us with your questions about the Student Developer Pack at https://education.github.com/contact.

**Closed as completed by tarebyte** 2017-06-28 22:52 UTC
